<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_length" value="0.04" />

    <xacro:macro name="box_inertia" params="m l w h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (h*h + l*l)}" ixy="0.0" ixz="0.0"
                 iyy="${(m/12) * (w*w + l*l)}" iyz="0.0"
                 izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0"
                     iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0"
                     izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="10.0" l="${base_length}" w="${base_width}" h="${base_height}"/>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="pivot_link" params="prefix">
        <link name="${prefix}_pivot_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius/2.0}" length="${base_height - 2.0 * wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="red" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius/2.0}" length="${base_height - 2.0 * wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${wheel_radius/2.0}" h="${base_height - 2.0 * wheel_radius}"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="back_right" />
    <xacro:wheel_link prefix="back_left" />

    <xacro:pivot_link prefix="front_right" />
    <xacro:pivot_link prefix="front_left" />
    <xacro:pivot_link prefix="back_right" />
    <xacro:pivot_link prefix="back_left" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_front_right_pivot_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_pivot_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} ${2.0 * wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_front_left_pivot_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_pivot_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} ${2.0 * wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_back_right_pivot_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_pivot_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} ${2.0 * wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_back_left_pivot_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_pivot_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} ${2.0* wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="front_right_pivot_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 0 ${-(base_height - 2.0 * wheel_radius)/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="front_left_pivot_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 0 ${-(base_height - 2.0 * wheel_radius)/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_right_wheel_joint" type="continuous">
        <parent link="back_right_pivot_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="0 0 ${-(base_height - 2.0 * wheel_radius)/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_left_wheel_joint" type="continuous">
        <parent link="back_left_pivot_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="0 0 ${-(base_height - 2.0 * wheel_radius)/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

</robot>